name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js (16)
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install Pacakges
        run: npm ci

      - name: Create ZIP
        env:
          CI: ""
        run: npm run grunt release

      - name: Run Semantic Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
